'use client'

import { type FormEvent, useMemo, useState } from 'react'
import { Avatar, invalidateAvatarUrl } from '@/components/avatar'
import { useAuth } from '@/components/auth-provider'
import { getSupabaseBrowserClient } from '@/lib/supabase/client'
import type { Position } from '@/lib/types'

const positions:Position[]=['GOALKEEPER','DEFENDER','MIDFIELDER','ATTACKER']
export default function MyProfilePage(){
  const {profile,refreshProfile}=useAuth(); const supabase=useMemo(()=>getSupabaseBrowserClient(),[]); const [message,setMessage]=useState('')
  if(!profile)return null
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const avatar=form.get('avatar');let avatarUrl=profile!.avatar_url;if(avatar instanceof File&&avatar.size){if(avatar.size>5_242_880){setMessage('Profile photo must be smaller than 5 MB.');return}if(!['image/jpeg','image/png','image/webp'].includes(avatar.type)){setMessage('Choose a JPG, PNG or WebP photo.');return}const extension=avatar.type==='image/png'?'png':avatar.type==='image/webp'?'webp':'jpg';const path=`${profile!.id}/profile.${extension}`;const upload=await supabase.storage.from('avatars').upload(path,avatar,{upsert:true,contentType:avatar.type});if(upload.error){setMessage('Could not upload that profile photo.');return}avatarUrl=`${supabase.storage.from('avatars').getPublicUrl(path).data.publicUrl}?v=${Date.now()}`;invalidateAvatarUrl(avatarUrl)}const {error}=await supabase.from('profiles').update({full_name:String(form.get('full_name')),nickname:String(form.get('nickname'))||null,bio:String(form.get('bio'))||null,preferred_position:form.get('preferred_position')||null,secondary_position:form.get('secondary_position')||null,goalkeeper_willing:form.get('goalkeeper_willing')==='on',avatar_url:avatarUrl}).eq('id',profile!.id);setMessage(error?'Could not save your profile.':'Profile saved.');if(!error)refreshProfile()}
  return <><header className="page-header"><div><p className="eyebrow">YOUR DETAILS</p><h1>Profile</h1></div></header><form className="card" onSubmit={save}><div className="player-row"><Avatar profile={profile} size="lg"/><div><h2 style={{marginBottom:'.25rem'}}>{profile.full_name}</h2><p className="muted">{profile.email}</p></div></div><label>Profile photo<input name="avatar" type="file" accept="image/jpeg,image/png,image/webp"/><span className="muted">JPG, PNG or WebP up to 5 MB.</span></label><div className="grid two"><label>Full name<input name="full_name" required defaultValue={profile.full_name}/></label><label>Nickname<input name="nickname" defaultValue={profile.nickname??''}/></label><label>Preferred position<select name="preferred_position" defaultValue={profile.preferred_position??''}><option value="">Choose position</option>{positions.map((p)=><option key={p}>{p}</option>)}</select></label><label>Secondary position<select name="secondary_position" defaultValue={profile.secondary_position??''}><option value="">None</option>{positions.map((p)=><option key={p}>{p}</option>)}</select></label></div><label className="inline-check"><input name="goalkeeper_willing" type="checkbox" defaultChecked={profile.goalkeeper_willing}/>Happy to play goalkeeper when needed</label><label>Bio<textarea name="bio" maxLength={300} defaultValue={profile.bio??''}/></label><button className="primary-button">Save profile</button>{message&&<p className="form-message">{message}</p>}</form></>
}
