'use client'

import Link from 'next/link'
import { type FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import { Avatar } from '@/components/avatar'
import { useAuth } from '@/components/auth-provider'
import { StatusPill } from '@/components/status-pill'
import { getSupabaseBrowserClient } from '@/lib/supabase/client'
import { effectiveStrength, generateFairTeams } from '@/lib/domain/team-generator'
import type { GameDatePoll, GameDatePollCount, Match, PlayerStats, Profile, StrengthPlayer, TeamSide, Venue } from '@/lib/types'

export default function AdminPage(){
  const {profile}=useAuth(); const supabase=useMemo(()=>getSupabaseBrowserClient(),[])
  const [pending,setPending]=useState<Profile[]>([]); const [matches,setMatches]=useState<Match[]>([]); const [venues,setVenues]=useState<Venue[]>([]); const [message,setMessage]=useState('')
  const [polls,setPolls]=useState<GameDatePoll[]>([]); const [pollCounts,setPollCounts]=useState<GameDatePollCount[]>([]); const [dateOptions,setDateOptions]=useState(['',''])
  const load=useCallback(async()=>{const [p,m,v,poll,count]=await Promise.all([supabase.from('profiles').select('*').eq('status','PENDING').order('full_name'),supabase.from('matches').select('*, venue:venues(*)').order('starts_at',{ascending:false}).limit(20),supabase.from('venues').select('*').eq('active',true).order('name'),supabase.from('game_date_polls').select('*, venue:venues(*), options:game_date_options(*)').order('created_at',{ascending:false}),supabase.from('game_date_poll_counts').select('*')]);setPending((p.data??[]) as Profile[]);setMatches((m.data??[]) as Match[]);setVenues((v.data??[]) as Venue[]);setPolls((poll.data??[]) as GameDatePoll[]);setPollCounts((count.data??[]) as GameDatePollCount[])},[supabase])
  // Initial admin data synchronization.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{if(profile?.role==='ADMIN')load()},[load,profile])
  if(profile?.role!=='ADMIN')return <div className="card empty-state"><h2>Admin access only</h2><p className="muted">This area is restricted.</p></div>
  async function setAccount(id:string,status:'APPROVED'|'REJECTED'){const {error}=await supabase.from('profiles').update({status}).eq('id',id);setMessage(error?'Could not update that account.':`Account ${status.toLowerCase()}.`);if(!error)load()}
  async function addVenue(event:FormEvent<HTMLFormElement>){event.preventDefault();const formElement=event.currentTarget;const form=new FormData(formElement);const {error}=await supabase.from('venues').insert({name:String(form.get('name')),address:String(form.get('address')),pitch:String(form.get('pitch'))||null});setMessage(error?'Could not create venue.':'Venue created.');if(!error){formElement.reset();load()}}
  async function addMatch(event:FormEvent<HTMLFormElement>){event.preventDefault();const formElement=event.currentTarget;const form=new FormData(formElement);const start=new Date(String(form.get('starts_at')));const deadlineValue=String(form.get('availability_deadline')||'');const {error}=await supabase.from('matches').insert({title:String(form.get('title')),starts_at:start.toISOString(),availability_deadline:deadlineValue?new Date(deadlineValue).toISOString():null,venue_id:String(form.get('venue_id'))||null,max_players:Number(form.get('max_players'))||null,status:'AVAILABILITY_OPEN',created_by:profile!.id});setMessage(error?'Could not create match.':'Match created and availability opened.');if(!error){formElement.reset();load()}}
  async function addDatePoll(event:FormEvent<HTMLFormElement>){event.preventDefault();const formElement=event.currentTarget;const form=new FormData(formElement);const options=dateOptions.filter(Boolean).map((value)=>new Date(value).toISOString());if(options.length<2)return setMessage('Add at least two possible dates.');const closeValue=String(form.get('closes_at')||'');const {error}=await supabase.rpc('create_game_date_poll',{p_title:String(form.get('title')),p_notes:String(form.get('notes')||''),p_venue_id:String(form.get('venue_id'))||null,p_closes_at:closeValue?new Date(closeValue).toISOString():null,p_options:options});setMessage(error?error.message:'Date poll opened.');if(!error){formElement.reset();setDateOptions(['','']);load()}}
  async function setPollStatus(id:string,status:'OPEN'|'CLOSED'){const {error}=await supabase.from('game_date_polls').update({status}).eq('id',id);setMessage(error?'Could not update the poll.':`Poll ${status.toLowerCase()}.`);if(!error)load()}
  return <><header className="page-header"><div><p className="eyebrow">CONTROL ROOM</p><h1>Admin</h1><p className="muted">People, fixtures and match operations.</p></div></header>{message&&<p className="form-message">{message}</p>}<div className="admin-metrics"><div className="card"><strong>{pending.length}</strong><span>Pending approvals</span></div><div className="card"><strong>{matches.filter((m)=>m.status==='AVAILABILITY_OPEN').length}</strong><span>Open fixtures</span></div><div className="card"><strong>{matches.filter((m)=>m.status==='VOTING_OPEN').length}</strong><span>Open votes</span></div><div className="card"><strong>{venues.length}</strong><span>Active venues</span></div></div>
  <section className="section"><div className="section-title"><h2>Pending approvals</h2></div><div className="card">{pending.length===0?<p className="muted">No players waiting.</p>:pending.map((player)=><div className="player-row" key={player.id}><Avatar profile={player}/><div className="player-copy"><strong>{player.full_name}</strong><small>{player.email}</small></div><div className="button-row"><button className="secondary-button" onClick={()=>setAccount(player.id,'APPROVED')}>Approve</button><button className="danger-button" onClick={()=>setAccount(player.id,'REJECTED')}>Reject</button></div></div>)}</div></section>
  <section className="grid two section"><form className="card" onSubmit={addDatePoll}><p className="eyebrow">FUTURE GAMES</p><h2>Suggest dates</h2><label>Poll title<input name="title" required defaultValue="Pick our next game"/></label><label>Venue<select name="venue_id"><option value="">TBC</option>{venues.map((v)=><option value={v.id} key={v.id}>{v.name}</option>)}</select></label><label>Voting closes (optional)<input name="closes_at" type="datetime-local"/></label><label>Note (optional)<textarea name="notes" maxLength={500} placeholder="Select every date you can make."/></label><div className="poll-date-builder"><span>Suggested kick-off times</span>{dateOptions.map((value,index)=><div className="button-row" key={index}><input aria-label={`Suggested date ${index+1}`} type="datetime-local" required value={value} onChange={(event)=>setDateOptions((current)=>current.map((item,itemIndex)=>itemIndex===index?event.target.value:item))}/>{dateOptions.length>2&&<button type="button" className="text-button" onClick={()=>setDateOptions((current)=>current.filter((_,itemIndex)=>itemIndex!==index))}>Remove</button>}</div>)}</div>{dateOptions.length<6&&<button type="button" className="secondary-button" onClick={()=>setDateOptions((current)=>[...current,''])}>Add another date</button>}<button className="primary-button section">Open date poll</button></form><div className="card"><p className="eyebrow">POLL CONTROL</p><h2>Current polls</h2>{polls.length===0?<p className="muted">No date polls yet.</p>:polls.map((poll)=><div className="admin-poll" key={poll.id}><div className="section-title"><div><strong>{poll.title}</strong><small>{poll.venue?.name??'Venue TBC'}</small></div><button className="secondary-button" onClick={()=>setPollStatus(poll.id,poll.status==='OPEN'?'CLOSED':'OPEN')}>{poll.status==='OPEN'?'Close':'Reopen'}</button></div>{[...(poll.options??[])].sort((a,b)=>a.starts_at.localeCompare(b.starts_at)).map((option)=><p key={option.id}><span>{new Date(option.starts_at).toLocaleString('en-GB',{dateStyle:'medium',timeStyle:'short'})}</span><strong>{pollCounts.find((count)=>count.option_id===option.id)?.vote_count??0} votes</strong></p>)}</div>)}</div></section>
  <section className="grid two section"><form className="card" onSubmit={addMatch}><p className="eyebrow">NEW FIXTURE</p><h2>Create match</h2><label>Title<input name="title" required defaultValue="Thursday Football"/></label><label>Kick-off<input name="starts_at" type="datetime-local" required/></label><label>Availability deadline<input name="availability_deadline" type="datetime-local"/></label><div className="grid two"><label>Venue<select name="venue_id"><option value="">TBC</option>{venues.map((v)=><option value={v.id} key={v.id}>{v.name}</option>)}</select></label><label>Max players<input name="max_players" type="number" min="2" max="50"/></label></div><button className="primary-button">Create match</button></form><form className="card" onSubmit={addVenue}><p className="eyebrow">VENUES</p><h2>Add venue</h2><label>Name<input name="name" required/></label><label>Address<input name="address" required/></label><label>Pitch (optional)<input name="pitch"/></label><button className="primary-button">Add venue</button></form></section>
  <section className="section"><div className="section-title"><h2>Match operations</h2></div><div className="match-list">{matches.map((match)=><Link className="card" href={`/dashboard/admin/matches/${match.id}`} key={match.id}><div className="date-tile"><span>{new Date(match.starts_at).toLocaleString('en-GB',{month:'short'})}</span><strong>{new Date(match.starts_at).getDate()}</strong></div><div><strong>{match.title}</strong><p className="muted" style={{margin:'.2rem 0 0'}}>{match.venue?.name??'Venue TBC'}</p></div><StatusPill status={match.status}/></Link>)}</div></section></>
}

export function toStrengthPlayer(player:Profile,stats?:PlayerStats):StrengthPlayer{return{id:player.id,name:player.nickname||player.full_name,preferredPosition:player.preferred_position,secondaryPosition:player.secondary_position,overallRating:stats?.overall_rating??null,recentForm:stats?.recent_form??null,ratedMatches:stats?.matches_played??0}}
export {effectiveStrength,generateFairTeams}
export type {TeamSide}
