'use client'

import { useParams } from 'next/navigation'
import { type FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import { Avatar } from '@/components/avatar'
import { StatusPill } from '@/components/status-pill'
import { useAuth } from '@/components/auth-provider'
import { effectiveStrength, generateFairTeams, recommendSide } from '@/lib/domain/team-generator'
import { getSupabaseBrowserClient } from '@/lib/supabase/client'
import type { Availability, Match, MatchStatus, PlayerStats, Profile, StrengthPlayer, TeamAssignment, TeamSide } from '@/lib/types'

interface GoalRow { id:string; scorer_id:string|null; team:TeamSide; quantity:number }
interface RatingAudit { id:string; voter_id:string; target_player_id:string; score:number }
interface VoteAudit { id:string; voter_id:string; target_player_id:string }
interface CommentAudit { id:string; author_id:string; body:string; anonymous:boolean; moderated:boolean }
interface WaitlistEntry { match_id:string; player_id:string; joined_at:string }

export default function AdminMatchPage(){
  const {id}=useParams<{id:string}>(); const {profile}=useAuth(); const supabase=useMemo(()=>getSupabaseBrowserClient(),[])
  const [match,setMatch]=useState<Match|null>(null); const [players,setPlayers]=useState<Profile[]>([]); const [availability,setAvailability]=useState<Availability[]>([]); const [waitlist,setWaitlist]=useState<WaitlistEntry[]>([]); const [assignments,setAssignments]=useState<TeamAssignment[]>([]); const [stats,setStats]=useState<PlayerStats[]>([]); const [goals,setGoals]=useState<GoalRow[]>([]); const [ratingAudit,setRatingAudit]=useState<RatingAudit[]>([]); const [voteAudit,setVoteAudit]=useState<VoteAudit[]>([]); const [commentAudit,setCommentAudit]=useState<CommentAudit[]>([]); const [message,setMessage]=useState('')
  const load=useCallback(async()=>{const [m,p,a,w,t,s,g,r,v,c]=await Promise.all([supabase.from('matches').select('*, venue:venues(*)').eq('id',id).single(),supabase.from('profiles').select('*').eq('status','APPROVED').order('full_name'),supabase.from('match_availability').select('*').eq('match_id',id),supabase.from('match_waitlist').select('*').eq('match_id',id).order('joined_at').order('player_id'),supabase.from('team_assignments').select('*').eq('match_id',id),supabase.from('player_stats').select('*'),supabase.from('goals').select('*').eq('match_id',id),supabase.from('ratings').select('*').eq('match_id',id),supabase.from('motm_votes').select('*').eq('match_id',id),supabase.from('comments').select('*').eq('match_id',id)]);setMatch(m.data as Match);setPlayers((p.data??[]) as Profile[]);setAvailability((a.data??[]) as Availability[]);setWaitlist((w.data??[]) as WaitlistEntry[]);setAssignments((t.data??[]) as TeamAssignment[]);setStats((s.data??[]) as PlayerStats[]);setGoals((g.data??[]) as GoalRow[]);setRatingAudit((r.data??[]) as RatingAudit[]);setVoteAudit((v.data??[]) as VoteAudit[]);setCommentAudit((c.data??[]) as CommentAudit[])},[id,supabase])
  // Initial match operation data synchronization.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{if(profile?.role==='ADMIN')load()},[load,profile])
  if(profile?.role!=='ADMIN')return <div className="card"><h2>Admin access only</h2></div>; if(!match)return <div className="spinner"/>
  const playing=availability.filter((item)=>item.status==='PLAYING').map((item)=>players.find((p)=>p.id===item.player_id)).filter((p):p is Profile=>Boolean(p))
  const asStrength=(player:Profile):StrengthPlayer=>{const summary=stats.find((s)=>s.player_id===player.id);return{id:player.id,name:player.nickname||player.full_name,preferredPosition:player.preferred_position,secondaryPosition:player.secondary_position,goalkeeperWilling:player.goalkeeper_willing,overallRating:summary?.overall_rating??null,recentForm:summary?.recent_form??null,ratedMatches:summary?.matches_played??0}}
  const teamPlayers=(side:TeamSide)=>assignments.filter((item)=>item.side===side).map((item)=>players.find((player)=>player.id===item.player_id)).filter((player):player is Profile=>Boolean(player))
  const currentRosters={bibs:teamPlayers('BIBS').map(asStrength),nonBibs:teamPlayers('NON_BIBS').map(asStrength)}
  const unassigned=playing.filter((player)=>!assignments.some((item)=>item.player_id===player.id))
  const estimatedAverage=(side:TeamSide)=>{const roster=side==='BIBS'?currentRosters.bibs:currentRosters.nonBibs;return roster.length?(roster.reduce((sum,player)=>sum+effectiveStrength(player),0)/roster.length).toFixed(1):'—'}
  async function status(next:MatchStatus){const changes:Record<string,unknown>={status:next};if(next==='VOTING_OPEN'){changes.voting_opens_at=new Date().toISOString();changes.voting_closes_at=new Date(Date.now()+86400000).toISOString()}if(next==='CANCELLED')changes.availability_locked=true;const {error}=await supabase.from('matches').update(changes).eq('id',id);setMessage(error?'Could not change match status.':`Match moved to ${next.toLowerCase().replaceAll('_',' ')}.`);if(!error)load()}
  async function generate(){
    if(playing.length<2)return setMessage('At least two players must be marked Playing.')
    const result=generateFairTeams(playing.map(asStrength))
    const rows=[...result.bibs.map((p)=>({match_id:id,player_id:p.id,side:'BIBS' as TeamSide})),...result.nonBibs.map((p)=>({match_id:id,player_id:p.id,side:'NON_BIBS' as TeamSide}))]
    const {error}=await supabase.from('team_assignments').upsert(rows,{onConflict:'match_id,player_id'})
    if(error)return setMessage('Could not save teams. The previous team sheet was kept.')
    const ids=rows.map((row)=>row.player_id).join(',')
    const {error:cleanupError}=await supabase.from('team_assignments').delete().eq('match_id',id).not('player_id','in',`(${ids})`)
    if(cleanupError)return setMessage('Teams saved, but old assignments could not be cleared. Please review the team sheet.')
    const {error:statusError}=await supabase.from('matches').update({status:'TEAMS_GENERATED',availability_locked:true}).eq('id',id)
    setMessage(statusError?'Teams saved, but the match status could not be updated.':`Teams generated: ${result.balance}% balance, ${result.difference.toFixed(2)} rating difference.`)
    void load()
  }
  async function move(playerId:string,side:TeamSide){const {error}=await supabase.from('team_assignments').update({side}).eq('match_id',id).eq('player_id',playerId);setMessage(error?'Could not move player.':'Team updated.');if(!error)load()}
  async function addLate(playerId:string,side:TeamSide){const {error}=await supabase.from('team_assignments').insert({match_id:id,player_id:playerId,side});setMessage(error?'Could not add this player to a team.':`Player added to ${side==='BIBS'?'Bibs':'Non-Bibs'}.`);if(!error)void load()}
  async function promote(playerId:string){if(!window.confirm(`Promote ${players.find((item)=>item.id===playerId)?.full_name??'this player'} from the waiting list?`))return;const {error}=await supabase.rpc('promote_waitlisted',{p_match:id,p_player:playerId});setMessage(error?'Could not promote: check that a Playing space is available.':'Player promoted to Playing.');if(!error)void load()}
  async function saveResult(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const {error}=await supabase.from('matches').update({bibs_score:Number(form.get('bibs_score')),non_bibs_score:Number(form.get('non_bibs_score')),status:'PLAYED'}).eq('id',id);setMessage(error?'Could not save result.':'Result saved.');if(!error)load()}
  async function addGoals(event:FormEvent<HTMLFormElement>){event.preventDefault();const formElement=event.currentTarget;const form=new FormData(formElement);const scorerId=String(form.get('scorer_id'));const assignment=assignments.find((item)=>item.player_id===scorerId);const quantity=Number(form.get('quantity'));if(!assignment)return setMessage('Choose a player on one of the teams.');const recorded=goals.filter((goal)=>goal.team===assignment.side&&goal.scorer_id!==scorerId).reduce((sum,goal)=>sum+goal.quantity,0);const limit=assignment.side==='BIBS'?match!.bibs_score:match!.non_bibs_score;if(limit!==null&&recorded+quantity>limit)return setMessage('Assigned goals cannot exceed that team’s score.');const {error}=await supabase.from('goals').upsert({match_id:id,scorer_id:scorerId,team:assignment.side,quantity},{onConflict:'match_id,scorer_id,team'});setMessage(error?'Could not save goals.':'Goalscorer updated.');if(!error){formElement.reset();load()}}
  async function moderateComment(commentId:string){const {error}=await supabase.from('comments').update({moderated:true,deleted_at:new Date().toISOString()}).eq('id',commentId);setMessage(error?'Could not moderate comment.':'Comment removed from player view.');if(!error)load()}
  const nameFor=(playerId:string|null)=>players.find((p)=>p.id===playerId)?.full_name??'Unknown player'
  return <><header className="page-header"><div><p className="eyebrow">MATCH OPERATIONS</p><h1>{match.title}</h1><p className="muted">{new Date(match.starts_at).toLocaleString('en-GB',{dateStyle:'full',timeStyle:'short'})}</p></div><StatusPill status={match.status}/></header>{message&&<p className="form-message">{message}</p>}
  <section className="card"><div className="section-title"><h2>Lifecycle</h2></div><div className="button-row"><button className="secondary-button" onClick={()=>status('AVAILABILITY_OPEN')}>Open availability</button><button className="secondary-button" onClick={()=>status('VOTING_OPEN')}>Open voting (24h)</button><button className="secondary-button" onClick={()=>status('FINALISED')}>Finalise</button><button className="danger-button" onClick={()=>status('CANCELLED')}>Cancel match</button></div></section>
  <section className="card section"><div className="section-title"><h2>Waiting list</h2><span className="muted">{waitlist.length} waiting · {playing.length}{match.max_players!==null?` / ${match.max_players}`:''} playing</span></div>{waitlist.length?waitlist.map((entry,index)=><div className="player-row" key={entry.player_id}><span className="ranking-position">{index+1}</span><div className="player-copy"><strong>{players.find((item)=>item.id===entry.player_id)?.full_name??'Player'}</strong></div><button className="secondary-button" onClick={()=>promote(entry.player_id)}>Promote</button></div>):<p className="muted">No players waiting.</p>}</section>
  <section className="section"><div className="section-title"><h2>Teams</h2><button className="primary-button" style={{width:'auto'}} onClick={generate}>{assignments.length?'Regenerate':'Generate fair teams'}</button></div><div className="grid two">{(['BIBS','NON_BIBS'] as TeamSide[]).map((side)=><div className={`card team-card team-${side.toLowerCase()}`} key={side}><h3>{side==='BIBS'?'Bibs':'Non-Bibs'}</h3><p className="muted">Estimated average strength: {estimatedAverage(side)} / 10</p>{assignments.filter((a)=>a.side===side).map((a)=>{const p=players.find((item)=>item.id===a.player_id);return p&&<div className="player-row" key={p.id}><Avatar profile={p}/><div className="player-copy"><strong>{p.nickname||p.full_name}</strong><small>{p.preferred_position?.toLowerCase()??'No position'}</small></div><button className="secondary-button" onClick={()=>move(p.id,side==='BIBS'?'NON_BIBS':'BIBS')}>Move</button></div>})}</div>)}</div>{assignments.length>0&&unassigned.length>0&&<div className="card section"><h3>Late arrivals</h3><p className="muted">These Playing members are not assigned yet. The suggestion balances the current team strengths.</p>{unassigned.map((player)=>{const recommended=recommendSide(currentRosters,asStrength(player));return <div className="player-row late-arrival-row" key={player.id}><Avatar profile={player}/><div className="player-copy"><strong>{player.nickname||player.full_name}</strong><small>Recommended: {recommended==='BIBS'?'Bibs':'Non-Bibs'}</small></div><div className="button-row"><button className="secondary-button" onClick={()=>addLate(player.id,'BIBS')}>Bibs</button><button className="secondary-button" onClick={()=>addLate(player.id,'NON_BIBS')}>Non-Bibs</button></div></div>})}</div>}</section>
  <section className="grid two section"><form className="card" onSubmit={saveResult}><p className="eyebrow">FULL TIME</p><h2>Record result</h2><div className="grid two"><label>Bibs score<input name="bibs_score" type="number" min="0" required defaultValue={match.bibs_score??''}/></label><label>Non-Bibs score<input name="non_bibs_score" type="number" min="0" required defaultValue={match.non_bibs_score??''}/></label></div><button className="primary-button">Save result</button></form><form className="card" onSubmit={addGoals}><p className="eyebrow">GOALSCORERS</p><h2>Assign goals</h2><label>Player<select name="scorer_id" required><option value="">Choose player</option>{assignments.map((a)=><option value={a.player_id} key={a.player_id}>{nameFor(a.player_id)} · {a.side==='BIBS'?'Bibs':'Non-Bibs'}</option>)}</select></label><label>Goals<input name="quantity" type="number" min="1" max="30" required/></label><button className="primary-button">Save goals</button>{goals.map((goal)=><p key={goal.id}>{nameFor(goal.scorer_id)} ×{goal.quantity}</p>)}</form></section>
  <section className="section"><div className="section-title"><h2>Private voting audit</h2><span className="muted">Admin only</span></div><div className="grid two"><div className="card"><h3>Ratings · {ratingAudit.length}</h3>{ratingAudit.length===0?<p className="muted">No ratings submitted.</p>:ratingAudit.map((rating)=><div className="player-row" key={rating.id}><div className="player-copy"><strong>{nameFor(rating.voter_id)} → {nameFor(rating.target_player_id)}</strong></div><strong>{Number(rating.score).toFixed(1)}</strong></div>)}</div><div className="card"><h3>MOTM votes · {voteAudit.length}</h3>{voteAudit.length===0?<p className="muted">No votes submitted.</p>:voteAudit.map((vote)=><div className="player-row" key={vote.id}><strong>{nameFor(vote.voter_id)} → {nameFor(vote.target_player_id)}</strong></div>)}</div></div></section>
  <section className="section"><div className="section-title"><h2>Comment moderation</h2></div><div className="card">{commentAudit.length===0?<p className="muted">No comments.</p>:commentAudit.map((comment)=><div className="player-row" key={comment.id}><div className="player-copy"><strong>{nameFor(comment.author_id)} {comment.anonymous&&<span className="muted">(anonymous publicly)</span>}</strong><small>{comment.body}</small></div>{!comment.moderated&&<button className="danger-button" onClick={()=>moderateComment(comment.id)}>Remove</button>}</div>)}</div></section></>
}
